# Mutation_analysis
# This program outputs interaction profile of wild and mutant residues
# You give a PDB and a set of mutations(single/multi, each mutation in one line)
# For every mutation(single/multi) a mutant will be generated by foldx
# Wild and mutant will be compared for the interaction profile of wild/mutant residues
# Suppose PDB=1GK9, u want to do 2 mutation
# Mutation-1: Single and Mutation-2 is a double
# You will get 3 PDB file, wild,mut1,mut2
# Comparison between wild and mut1 will output 2 line of int.profile, one for wild and another for mutant
# Comparison between wild and mut2 will output 4 line of int.profile, two for wild and two for mutant

# For every session a working directory specific to that session (set by prefix) will be created
# The wild PDB will be loaded in the R workspace
# All mutant pdb will be generated in the workdir with name mutant1.pdb, mutant2.pdb etc
# We need only 2 information, chain and resno to fetch interactions


prefix="Mutation_allcombine1";

####################### All directories
script_dir="/home/priyabrata/Work/ProtTS/SASMAT_ason_29sept2013_before4th5thPres/Script_dir/";
work_dir="/home/priyabrata/Work/ProtTS/workdir/";
pdb_dir="/data1/mut/";
output_dir="/home/priyabrata/Work/ProtTS/SASMAT_ason_29sept2013_before4th5thPres/CompStabAna/out/";

# Load all Libraries and sources
loadsource=function(script_dir,file)
{
	source(paste(script_dir,file,sep="",collapse=""));
}

library("bio3d");
library("igraph");
loadsource(script_dir,"PATH.r");
loadsource(script_dir,"dssp.r");
loadsource(script_dir,"naccess.r");
loadsource(script_dir,"ionic.r");
loadsource(script_dir,"general.r");
loadsource(script_dir,"aroaro.r");
loadsource(script_dir,"aroS.r");
loadsource(script_dir,"catpi.r");
loadsource(script_dir,"disulfide.r");
loadsource(script_dir,"hbond.r");
loadsource(script_dir,"Hphob.r");
loadsource(script_dir,"intprofile.r");

# Setting sfor which programs to run
calc_uniqch=0;

######################## Set the working directory
work_dir=paste(work_dir,prefix,sep="",collapse="");
createDir(work_dir);
setwd(work_dir);

# Program parameters
aroarolow=4.5;
aroarohigh=7.0;
aroarodihed=30.0;
usedihed=1;
ioncut=3.2;
aroscut=5.3;
hpcut=5.0;
# CATion-pi mode=1: pdb 2:upload
catpimode=1;

# Output directory
dirpath=paste(output_dir,prefix,sep="",collapse="");
dirpath.detail=paste(dirpath,"/","Details",sep="",collapse="");
sumpath=paste(dirpath,"/","Mutation_summary.txt",sep="",collapse="");
cat("",file=sumpath,sep="",eol="");

# create root directory
createDir(dirpath);
createDir(dirpath.detail);




#########################################################################################################################################################

####################
# Load the wild PDB file
# Parse the mutation file
# Create the mutants in the working directory
# Store the filename of wild and mutant in an array and name the variable to filenames. The order is importnat
# Set the pdb directory to the working directory.
# There is no harm in setting pdb_dir to work_dir coz we have already got the filename variable
# So read.pdb() will read the pdbnames in the filenames vector and load in the worksapce
####################

# tempprefixes
count=1;
dsspprefix=paste(prefix,"_dssp",count,sep="",collapse="");
naccprefix=paste(prefix,"_nacc",count,sep="",collapse="");
hbplusprefix=paste(prefix,"_hbplus",count,sep="",collapse="");
promotifprefix=paste(prefix,"_promotif",count,sep="",collapse="");
procheckprefix=paste(prefix,"_procheck",count,sep="",collapse="");
captureprefix=paste(prefix,"_capture",count,sep="",collapse="");

# In the filenames variable [1] is wild type and [2] is first mutant [3]:2nd mutant
filenames=c("1A1X.pdb","mut1.pdb","mut2.pdb");
mutfile="/data1/mut/mut.txt";
mut.lines=readLines(mutfile);

# Read the wild pdb file run DSSP and nacc
wildPDB="";wild_nacc="";wild_DSSP="";mutPDB="";	
wildPDB=read.pdb(paste(pdb_dir,"/",filenames[1],sep=""),maxlines=100000,verbose=FALSE); # read the wild pdb file filenames[1]
wild_nacc=naccess(wildPDB,naccpath,prefix=naccprefix); # Runs naccess
wild_DSSP=dssp_new(wildPDB,exepath=dssppath,prefix=dsspprefix); #Runs DSSP
wild_status.DSSP=0;if(is.list(wild_DSSP)){wild_status.DSSP=1;}
wild_status.nacc=0;if(is.list(wild_nacc)){wild_status.nacc=1;}
wild_intList=calc_interaction(pdb=wildPDB,DSSP=wild_DSSP,nacc=wild_nacc,status.DSSP=wild_status.DSSP,status.nacc=wild_status.nacc); # calculate interaction list

for(mutno in 2:length(filenames))
{
	sumpath.int=paste(dirpath.detail,"/Mutant",(mutno-1),"_details.txt",sep="",collapse="");
	flag=0;
	cat("",file=sumpath.int,sep="",eol="");				
	# Read the mutant pdb file
	mutPDB=read.pdb(paste(pdb_dir,"/",filenames[mutno],sep=""),maxlines=100000,verbose=FALSE); # read the wild pdb file filenames[1]

	mut_nacc=naccess(mutPDB,naccpath,prefix=naccprefix); # Runs naccess
	mut_DSSP=dssp_new(mutPDB,exepath=dssppath,prefix=dsspprefix); #Runs DSSP
	mut_status.DSSP=0;if(is.list(mut_DSSP)){mut_status.DSSP=1;}
	mut_status.nacc=0;if(is.list(mut_nacc)){mut_status.nacc=1;}
	mut_intList=calc_interaction(pdb=mutPDB,DSSP=mut_DSSP,nacc=mut_nacc,status.DSSP=mut_status.DSSP,status.nacc=mut_status.nacc); # calculate interaction list

	mutlist=unlist(strsplit(mut.lines[mutno-1],",")) # For 2nd mutant i.e. mutno=2, filenames[mutno]="mut1.txt" which corresponds to first line of mutfile so mut.line[mutno-1]
	mutlist=gsub(";","",mutlist);
	
	wild_patmat=cbind(substr(mutlist,2,2),substr(mutlist,3,nchar(mutlist)-1),substr(mutlist,1,1));
	mut_patmat=cbind(substr(mutlist,2,2),substr(mutlist,3,nchar(mutlist)-1),substr(mutlist,nchar(mutlist),nchar(mutlist)));

	# for a double mutant "VA18C,VA92C;" wild_patmat will be
	#[,1] [,2] [,3]
	#[1,] "A"  "18" "V" 
	#[2,] "A"  "92" "V" 
	# we use apply function and get a list of 2 index 
	# wild_intprof[[1]] is a profile list for first wildtpe residue and wild_intprof[[2]] is profile for second res

	wild_intprof=apply(wild_patmat,1,calc_intProfile,wild_intList)
	mut_intprof=apply(mut_patmat,1,calc_intProfile,mut_intList)
	
	# Loop over eadh mutantion, if double then it will loop twice
	for(mutind in 1:length(wild_intprof))
	{
	# For each mutation, get wild and mutant interaction profile "no of type-interation/0"
	
	temp.wild=apply(matrix(1:11,ncol=1),1,function(x){ temp.val=wild_intprof[[mutind]][[x]]; if(is.matrix(temp.val)){return(nrow(temp.val))}else{return(0);};});
	temp.mut=apply(matrix(1:11,ncol=1),1,function(x){ temp.val=mut_intprof[[mutind]][[x]]; if(is.matrix(temp.val)){return(nrow(temp.val))}else{return(0);};} );
	#wild pdb
	cat(c(filenames[1],wild_patmat[mutind,],temp.wild),sep="\t",eol="\n",file=sumpath,append=TRUE);
	#mutant
	cat(c(filenames[mutno],mut_patmat[mutind,],temp.mut),sep="\t",eol="\n",file=sumpath,append=TRUE);
		if(sum(temp.wild)>0)
		{
		flag=1;
		cat(paste(c("\nWild:",wild_patmat[mutind,],"\n--------\n"),sep="",collapse=""),sep="\t",eol="\n",file=sumpath.int,append=TRUE);
		write_intprofile(wild_intprof[[mutind]],sumpath.int);
		}
		if(sum(temp.mut)>0)
		{
		flag=1;
		cat(paste(c("\nMut:",mut_patmat[mutind,],"\n--------\n"),sep="",collapse=""),sep="\t",eol="\n",file=sumpath.int,append=TRUE);
		write_intprofile(mut_intprof[[mutind]],sumpath.int);
		}
	}
	if(flag==0){unlink(sumpath.int);}
}



